# Generated by Django 4.2.13 on 2026-05-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('parsed_skills', models.JSONField(default=list, help_text='List of skill strings extracted by NLP')),
                ('parsed_keywords', models.JSONField(default=list, help_text='List of important keywords extracted by NLP')),
                ('experience_required', models.CharField(blank=True, default='', help_text='e.g. 3-5 years', max_length=100)),
                ('education_required', models.CharField(blank=True, choices=[('', 'Not specified'), ('any', 'Any'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], default='', help_text='Minimum education level required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
