# Generated by Django 4.2.13 on 2026-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='education_required',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('any', 'Any'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='experience_required',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='parsed_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='parsed_skills',
            field=models.JSONField(default=list),
        ),
    ]
